version: "3.9"
services:
  proxywithfrontend:
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile
    volumes:
      - data:/vol
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      # needs customizing to run on server
      - API_URL=http://localhost/api/
      - WEBSOCKET_URL=ws://localhost/ws/

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app
      - data:/vol
    environment:
      - DEBUG=0
      # needs customizing to run on server
      - SECRET_KEY=samplekey
      - ALLOWED_HOSTS=localhost

volumes:
  data: