version: "3.9"
services:
  proxywithfrontend:
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile
    volumes:
      - data:/vol
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      # needs customizing before run on a server
      - API_URL=http://localhost/api/
      - WEBSOCKET_URL=ws://localhost/ws/

  backend:
    build:
      context: ./backend
    depends_on:
      - database
    volumes:
      - ./backend/app:/app
      - data:/vol
    environment:
      - DEBUG=0
      - DB_HOST=database
      - DB_NAME=proddb
      - DB_USER=admin
      # needs customizing before run on a server
      - DB_PASS=changeme
      - SUPER_USER_NAME=admin
      - SUPER_USER_EMAIL=admin@example.com
      - SUPER_USER_PASSWORD=changeme
      - SECRET_KEY=changeme
      - ALLOWED_HOSTS=localhost

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=proddb
      - POSTGRES_USER=admin
      # needs customizing before run on a server
      - POSTGRES_PASSWORD=changeme
    volumes:
      - prod-db-data:/var/lib/postgresql/data

volumes:
  data:
  prod-db-data: