version: "3.9"
services:
  proxywithfrontend:
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile
      args:
        # needs customizing before run on a server
        - API_URL=${FRONTEND_API_URL}
        - WEBSOCKET_URL=${FRONTEND_WEBSOCKET_URL}
    volumes:
      - data:/vol
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    depends_on:
      - database
    volumes:
      - data:/vol
    environment:
      - DEBUG=0
      - DB_HOST=database
      - DB_NAME=proddb
      - DB_USER=admin
      - DB_PASS=${DATABASE_PASSWORD}
      - SECRET_KEY=${BACKEND_SECRET_KEY}
      - ALLOWED_HOSTS=${BACKEND_ALLOWED_HOSTS}
      # Super user is created automaticly only once on the first run. If you want to create another one
      # with those settings, use python manage.py createsuperuser --noinput in a container.
      # For security reasons, I recommend removing this information after super user has been created
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=changeme
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=proddb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - prod-db-data:/var/lib/postgresql/data

volumes:
  data:
  prod-db-data: