# Generated by Django 4.0.4 on 2022-11-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default='noimage.png', upload_to='profile_pictures'),
        ),
    ]
