# Generated by Django 4.1.5 on 2023-01-11 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_alter_message_readby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='readBy',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
