# Generated by Django 4.1.5 on 2023-01-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_rename_content_message_content_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='readBy',
            new_name='read_by',
        ),
    ]
